DROP TABLE BOARD;
DROP TABLE PRODUCT;
DROP TABLE ORDERS;
DROP TABLE COMPANY;
DROP TABLE MEMBER;

DROP SEQUENCE MEMBER_SEQ;
DROP SEQUENCE COMPANY_SEQ;
DROP SEQUENCE ORDERS_SEQ;
DROP SEQUENCE PRODUCT_SEQ;
DROP SEQUENCE BOARD_SEQ;

CREATE SEQUENCE MEMBER_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 999999 NOCACHE NOCYCLE;
CREATE SEQUENCE COMPANY_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 999999 NOCACHE NOCYCLE;
CREATE SEQUENCE ORDERS_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 999999 NOCACHE NOCYCLE;
CREATE SEQUENCE PRODUCT_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 999999 NOCACHE NOCYCLE;
CREATE SEQUENCE BOARD_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 999999 NOCACHE NOCYCLE;

CREATE TABLE MEMBER(
	MNO NUMBER PRIMARY KEY,
	MID VARCHAR2(30) NOT NULL UNIQUE,
	MPW VARCHAR2(30) NOT NULL,
	MNAME VARCHAR2(30) NOT NULL,
	MEMAIL VARCHAR2(200) NOT NULL UNIQUE,
	MPHONE VARCHAR2(20), 
	MADDRESS VARCHAR2(200),
	MREGDATE DATE DEFAULT SYSDATE
);

CREATE TABLE BOARD(
	BNO NUMBER PRIMARY KEY,
	MID VARCHAR2(30) REFERENCES MEMBER (MID),
	BTITLE VARCHAR2(1000) NOT NULL,
	BCONTENT VARCHAR2(4000),
--	BFILENAME VARCHAR2(1000),
--	BPW VARCHAR2(30),
	BIP VARCHAR2(30),	-- 작성IP
	BHIT NUMBER DEFAULT 0,		
	BLASTMODIFY DATE DEFAULT SYSDATE,	-- 최종 수정일
	BREGDATE DATE DEFAULT SYSDATE,		-- 최초 작성일
	BDELETE NUMBER DEFAULT 0,			-- 삭제여부	(삭제: -1, 정상: 0)
	BGROUP NUMBER DEFAULT 0,		-- 게시글 그룹 (어떤 게시글과 거기에 달린 댓글들은 모두 같은 그룹)
	BGROUPORD NUMBER DEFAULT 0,	-- 게시글 순서 (같은 그룹에서 표시할 순서)
	BDEPTH NUMBER DEFAULT 0		-- 게시글/댓글 구분 (게시글: 0, 댓글: 1 이상)
);

CREATE TABLE COMPANY(
	CNO NUMBER PRIMARY KEY,
	CNAME VARCHAR2(100) NOT NULL UNIQUE,
	CPHONE VARCHAR2(20),
	CADDRESS VARCHAR2(200)
--	,
--	CBANK VARCHAR2(100) NOT NULL,
--	CACCOUNTNUMBER VARCHAR2(100) NOT NULL,
--	CACCOUNTHOLDER VARCHAR2(30) NOT NULL
);

CREATE TABLE ORDERS(
	ONO NUMBER PRIMARY KEY,
	MID VARCHAR2(30) REFERENCES MEMBER (MID),
	OREGDATE DATE DEFAULT SYSDATE
);

CREATE TABLE PRODUCT(
	PNO NUMBER PRIMARY KEY,
	ONO	NUMBER REFERENCES ORDERS (ONO),
	CNO NUMBER REFERENCES COMPANY (CNO),
	PPRICE NUMBER DEFAULT -1,
	PREGDATE DATE DEFAULT SYSDATE,
	PSALE NUMBER DEFAULT 0
);

INSERT INTO MEMBER VALUES (MEMBER_SEQ.NEXTVAL, 'admin', '1111','관리자','admin@home.com','010-0000-0000','서울',SYSDATE);
INSERT INTO MEMBER VALUES (MEMBER_SEQ.NEXTVAL, 'user1', '1111','에밀리','user1@home.com','010-1111-1111','경기',SYSDATE);
INSERT INTO MEMBER VALUES (MEMBER_SEQ.NEXTVAL, 'user2', '1111','앨리스','user2@home.com','010-2222-2222','인천',SYSDATE);
INSERT INTO MEMBER VALUES (MEMBER_SEQ.NEXTVAL, 'user3', '1111','사만다','user3@home.com','010-3333-3333','부산',SYSDATE);

INSERT INTO BOARD(BNO, MID, BTITLE, BCONTENT, BIP) VALUES (BOARD_SEQ.NEXTVAL, 'admin', '공지사항1', '안녕하세요', '0.0.0.0');
INSERT INTO BOARD(BNO, MID, BTITLE, BCONTENT, BIP) VALUES (BOARD_SEQ.NEXTVAL, 'admin', '공지사항2', '어서오세요', '0.0.0.0');
INSERT INTO BOARD(BNO, MID, BTITLE, BCONTENT, BIP) VALUES (BOARD_SEQ.NEXTVAL, 'admin', '공지사항3', '반갑습니다', '0.0.0.0');
INSERT INTO BOARD(BNO, MID, BTITLE, BCONTENT, BIP) VALUES (BOARD_SEQ.NEXTVAL, 'user1', '글쓰기1', '본문입니다', '0.0.0.0');
INSERT INTO BOARD(BNO, MID, BTITLE, BCONTENT, BIP) VALUES (BOARD_SEQ.NEXTVAL, 'user1', '글쓰기2', '본문입니다', '0.0.0.0');
INSERT INTO BOARD(BNO, MID, BTITLE, BCONTENT, BIP) VALUES (BOARD_SEQ.NEXTVAL, 'user1', '글쓰기3', '본문입니다', '0.0.0.0');
INSERT INTO BOARD(BNO, MID, BTITLE, BCONTENT, BIP) VALUES (BOARD_SEQ.NEXTVAL, 'user1', '글쓰기4', '본문입니다', '0.0.0.0');
INSERT INTO BOARD(BNO, MID, BTITLE, BCONTENT, BIP) VALUES (BOARD_SEQ.NEXTVAL, 'user2', '게시글1', '본문입니다', '0.0.0.0');
INSERT INTO BOARD(BNO, MID, BTITLE, BCONTENT, BIP) VALUES (BOARD_SEQ.NEXTVAL, 'user2', '게시글2', '본문입니다', '0.0.0.0');
INSERT INTO BOARD(BNO, MID, BTITLE, BCONTENT, BIP) VALUES (BOARD_SEQ.NEXTVAL, 'user2', '게시글3', '본문입니다', '0.0.0.0');
INSERT INTO BOARD(BNO, MID, BTITLE, BCONTENT, BIP) VALUES (BOARD_SEQ.NEXTVAL, 'user2', '게시글4', '본문입니다', '0.0.0.0');
INSERT INTO BOARD(BNO, MID, BTITLE, BCONTENT, BIP) VALUES (BOARD_SEQ.NEXTVAL, 'user3', '게시글1', '본문입니다', '0.0.0.0');
INSERT INTO BOARD(BNO, MID, BTITLE, BCONTENT, BIP) VALUES (BOARD_SEQ.NEXTVAL, 'user3', '게시글2', '본문입니다', '0.0.0.0');
INSERT INTO BOARD(BNO, MID, BTITLE, BCONTENT, BIP) VALUES (BOARD_SEQ.NEXTVAL, 'user3', '게시글3', '본문입니다', '0.0.0.0');
INSERT INTO BOARD(BNO, MID, BTITLE, BCONTENT, BIP) VALUES (BOARD_SEQ.NEXTVAL, 'user3', '게시글4', '본문입니다', '0.0.0.0');

INSERT INTO BOARD(BNO, MID, BTITLE, BCONTENT, BIP, BGROUP, BGROUPORD, BDEPTH) VALUES (BOARD_SEQ.NEXTVAL, 'user1', '댓글1', '댓글1입니다', '0.0.0.0', 1, 3, 1);
INSERT INTO BOARD(BNO, MID, BTITLE, BCONTENT, BIP, BGROUP, BGROUPORD, BDEPTH) VALUES (BOARD_SEQ.NEXTVAL, 'user2', '댓글2', '댓글2입니다', '0.0.0.0', 1, 1, 1);
INSERT INTO BOARD(BNO, MID, BTITLE, BCONTENT, BIP, BGROUP, BGROUPORD, BDEPTH) VALUES (BOARD_SEQ.NEXTVAL, 'user3', '댓글3', '댓글3입니다', '0.0.0.0', 1, 2, 2);


